- hosts: localhost
  become: yes
  tasks:
   - name: Install Git
     yum: name=git state=present
   - name: git clone
     git:
      repo: 'https://github.com/akshu20791/DevOpsClassCodes.git'
      dest: /home/ansible/gradle-web-app